{
  lib,
  config,
  pkgs,
  tailscaleNodes,
  ...
}:
let
  hostName = config.networking.hostName;
  tailscaleSecret = tailscaleNodes.${hostName} or null;
in
{
  # List packages installed in system profile. To search, run:
  # Only install Tailscale packages if this specific node uses it
  environment.systemPackages = lib.optionals (tailscaleSecret != null) [
    pkgs.tailscale
    pkgs.tailscale-systray
  ];

  sops.secrets = lib.optionalAttrs (tailscaleSecret != null) {
    ${tailscaleSecret} = { };
  };

  # Tailscale and its systemd authentication service
  services.tailscale = lib.mkIf (tailscaleSecret != null) {
    enable = true;
    authKeyFile = config.sops.secrets.${tailscaleSecret}.path;
    extraSetFlags = [ "--accept-dns=false" ]; # to avoid overriding DNS configuration
    # cat /etc/resolv.conf
    # # Generated by resolvconf
    # search tigris-bee.ts.net
    # nameserver 100.100.100.100
    # options edns0
  };

  # Fix the systemd deadlock during activation
  systemd.services = {
    # 1. Prevent tailscaled from blocking the NixOS switch if the interface drops
    tailscaled.stopIfChanged = false;

    # 2. Ensure the autoconnect service waits for SOPS to decrypt the key
    tailscale-autoconnect = lib.mkIf (tailscaleSecret != null) {
      after = [
        "sops-secrets.target"
        "network-pre.target"
      ];
      wants = [ "sops-secrets.target" ];
    };
  };
}
